#pragma once
#ifndef SQUADLOADER_H
#define SQUADLOADER_H

#include "../api/ApiModels.h"
#include <QVector>
#include <QString>

/**
 * SquadLoader
 *
 * Loads all 2026 FIFA World Cup squad JSON files bundled as Qt resources
 * under :/squads/ (generated by tools/scrape_squads.py).
 *
 * Usage:
 *   SquadLoader loader;
 *   QVector<Models::Team> teams = loader.loadAll();
 */
class SquadLoader
{
public:
    SquadLoader() = default;

    /** Load all teams from :/squads/teams_index.json + per-team files. */
    QVector<Models::Team> loadAll() const;

    /** Load a single team file (resource path, e.g. ":/squads/brazil.json"). */
    Models::Team loadTeam(const QString &resourcePath) const;

private:
    Models::PlayerStats defaultStats() const;
    QString positionFromCode(const QString &code) const;
};

#endif // SQUADLOADER_H
